version: '3.8'

services:
  skylogger-pro:
    build: .
    container_name: skylogger-pro-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Optional: Mount source code for development
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - skylogger-network

networks:
  skylogger-network:
    driver: bridge